# Generated by Django 4.2.4 on 2023-09-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_student_attendence_delete_sattendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='st_id',
        ),
    ]
