# Generated by Django 4.2.4 on 2023-09-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_student_attendence_st_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendence',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.student'),
        ),
    ]
