# Generated by Django 4.2.4 on 2023-09-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_student_attendence_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendence',
            name='attendence',
            field=models.IntegerField(default=1, max_length=1, null=True),
        ),
    ]
