# Generated by Django 4.2.4 on 2023-09-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_student_attendence_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='sid',
        ),
    ]
