# Generated by Django 4.2.4 on 2023-09-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_student_attendence_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendence',
            name='sid',
        ),
    ]
