# Generated by Django 4.2.4 on 2023-09-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_student_attendence_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendence',
            name='sid',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='userapp.student'),
            preserve_default=False,
        ),
    ]
